  - name: configure user server
    hosts:  user
    become: yes
    tasks:
      - name: disable nodejs
        ansible.builtin.command:  dnf module disable nodejs -y

      - name: enable nodejs
        ansible.builtin.command:  dnf module enable nodejs:20 -y


      - name: install nodejs
        ansible.builtin.dnf:
          name: nodejs
          state:  present

      - name: create roboshop system user
        ansible.builtin.user:
          name: roboshop
          shell:  /sbin/nologin
          home: /app
          system: true

      - name: create home directory
        ansible.builtin.file:
          path: /app
          state:  directory

      - name: download the source code
        ansible.builtin.get_url:
          url:  https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
          dest: /tmp/user.zip

      - name: extract the file
        ansible.builtin.unarchive:
          src:  /tmp/user.zip
          dest: /app
          remote_src: yes

      - name: install dependancies
        community.general.npm:
          path: /app

      - name: copy servie config file
        ansible.builtin.copy:
          src:  user.service
          dest: /etc/systemd/system/user.service

      - name: systemctl deamon reload
        ansible.builtin.systemd_service:
          daemon_reload:  true

      - name: start and enable user
        ansible.builtin.service:
          name: user
          state:  started
          enabled:  yes                         